title: Jacob Smith
url: http://systemist.org

owner:
  name: Jacob Smith
  email: jacob@jacobsmith.io

theme:

exclude:
# default excludes, can be removed in > 4.0
- .sass-cache/
- .jekyll-cache/
- gemfiles/
- Gemfile
- Gemfile.lock
# - node_modules/
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
# custom excludes
- scripts
